# COPY this example content to .secrets.toml
[default]
secret_key = "<secret_key>"

[development]
sqlalchemy_database_uri = 'postgresql://<user>:<password>@<host>/<database>'

[production]
sqlalchemy_database_uri = 'postgresql://<user>:<password>@<host>/<database>'

[testing]
sqlalchemy_database_uri = 'postgresql://<user>:<password>@<host>/<database>'